[table_suffix]
baseline = "_baseline"
timeseries = "_timeseries"
upgrades = "_upgrades"

[column_prefix]
characteristics = "build_existing_model."
output = "simulation_output_report."


[column_names]
building_id = "building_id"
sample_weight = ""
sqft = "build_existing_model.geometry_floor_area"
timestamp = "time"
completed_status = "completed_status"
unmet_hours_cooling_hr = ""
unmet_hours_heating_hr = ""
fuel_totals = [
    "simulation_output_report.total_site_electricity_kwh",
    "simulation_output_report.total_site_energy_mbtu",
    "simulation_output_report.total_site_natural_gas_therm",
    "simulation_output_report.total_site_other_fuel_mbtu"]

[completion_values]
success = "Success"
fail = "Fail"
unapplicable = "Invalid"

[structure]
unapplicables_have_ts = "false"
