[table_suffix]
baseline = "_baseline"
timeseries = "_timeseries"
upgrades = "_upgrades"

[column_prefix]
characteristics = "build_existing_model."
output = "report_simulation_output."


[column_names]  
building_id = "building_id"
sample_weight = "build_existing_model.sample_weight"
sqft = "build_existing_model.geometry_floor_area"    
timestamp = "time"
completed_status = "completed_status"
unmet_hours_cooling_hr = "report_simulation_output.unmet_hours_cooling_hr"
unmet_hours_heating_hr = "report_simulation_output.unmet_hours_heating_hr"
map_eiaid_column = "county"
fuel_totals = [
               'report_simulation_output.energy_use_total_m_btu',
               'report_simulation_output.fuel_use_coal_total_m_btu',
               'report_simulation_output.fuel_use_electricity_total_m_btu',
               'report_simulation_output.fuel_use_fuel_oil_total_m_btu',
               'report_simulation_output.fuel_use_natural_gas_total_m_btu',
               'report_simulation_output.fuel_use_propane_total_m_btu',
               'report_simulation_output.fuel_use_wood_cord_total_m_btu',
               'report_simulation_output.fuel_use_wood_pellets_total_m_btu'
               ]

[completion_values]
success = "Success"
fail = "Fail"
inapplicable = "Invalid"

[structure]
inapplicables_have_ts = "false"
