name: Tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    name: Tests - Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
         python-version: ${{ matrix.python-version}}
      - name: Install buildstock_query
        run: pip install -e .[dev]
      - name: Pytest
        run: pytest -vv
      - name: Lint
        run: flake8 buildstock_query