name: Tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11']
    name: Tests - Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
         python-version: ${{ matrix.python-version}}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-duration-seconds: 1200
          role-session-name: MySession
      - name: Who am I?
        run: aws sts get-caller-identity
      - name: Install buildstock_query
        run: pip install -e .[dev]
      - name: Pytest
        run: python -m pytest -vv
      - name: Lint
        run: flake8 buildstock_query
